# Generated by Django 5.1.5 on 2025-02-19 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contributor',
            new_name='Investor',
        ),
        migrations.RenameField(
            model_name='contribution',
            old_name='contributor',
            new_name='owner',
        ),
    ]
