# Generated by Django 5.1.5 on 2025-02-19 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_contributor_investor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='owner',
            new_name='investor',
        ),
    ]
