# Generated by Django 5.1.5 on 2025-02-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_owner_contribution_investor'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='total_contributions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
