# Generated by Django 5.1.5 on 2025-02-19 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_transaction_delete_contribution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='contributed_at',
            new_name='created_at',
        ),
    ]
