# Generated by Django 5.1.5 on 2025-02-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_contributed_at_transaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='reason',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
