# Generated by Django 5.1.5 on 2025-02-25 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_transaction_notes_transaction_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='reason',
        ),
    ]
